---
name: Build Application Image

permissions:
  id-token: write
  contents: write
  issues: read
  checks: write

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build Docker image
        run: |
          docker build -t my-docker-username/biblioteca-infantil:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push my-docker-username/biblioteca-infantil:${{ github.sha }}